config/routes.rb
Rails.application.routes.draw do

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :devices do
    post :validate, on: :collection
  end
  resources :shifts do
    member do
      get :change_status
    end
    post :validate, on: :collection
  end
  mount ActionCable.server => '/cable'

  get 'errors/not_found'

  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # Sidekiq background jobs ui
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'provisioning', to:'provisioning#index', as: :provisioning

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  # root 'dashboard#index'


  root :to => 'trips#index', :constraints => lambda { |request| request.env['warden'].user&.role == 'line_manager' }
  root :to => 'dashboard#index'

  resources :dashboard do
    collection do
      get :ota
      get :costs
      get :exceptions
      get :completed_trips
      get :fleet_utilization
    end
  end

  # ------------------------- Companies ------------------------------

  resources :logistics_companies do
    collection do
      get :get_all
    end
  end
  put '/logistics_companies/operator/:id', to: 'logistics_companies#operator_edit'
  delete '/logistics_companies/operator/:id', to: 'logistics_companies#operator_delete'    
  
  resources :employee_companies do
    collection do
      get :get_all
    end
  end

  resources :business_associates do
    member do
      put :update_ba
    end
    collection do
      post :details
    end
  end

  # --------------------------- Users --------------------------------
  resources :user
  get 'users', to: 'user#index'

  get '/profile', to: 'home#profile_edit', as: :user_profile_edit
  get '/site_list', to: 'sites#site_list'
  patch '/profile', to: 'home#profile_update', as: :user_profile_update
  get '/initiate_call', to: 'home#initiate_call'
  post '/update_last_active_time', to: 'home#update_last_active_time'
  post '/exotel_callback', to: 'home#exotel_callback'
  get '/badge_count', to: 'home#badge_count'
  post '/auto_cluster', to: 'home#auto_cluster'
  post '/decluster', to: 'employee_clusters#decluster'
  post '/auto_clustering_via_service', to: 'employee_trips#auto_clustering_via_service'
  get '/offline_sms', to: 'home#offline_sms_get'
  post '/offline_sms', to: 'home#offline_sms_post'
  get '/sorted_routes', to: 'home#sorted_routes'

  get '/release_info', to: 'home#release_info'

  resources :operators
  resources :employers
  resources :line_managers do
    member do
      get :invite
      get :edit_list
      post :update_employee_list
    end
  end
  resources :transport_desk_managers
  resources :drivers do
    member do
      get :invite
      post :stop_on_leave
      get :checklist
      post :update_checklist
    end
    post :validate, on: :collection
  end
  resources :employees do
    member do
      get :schedule, to: 'employee_schedules#edit'
      get :trips, to: 'employee_trips#trips'
      get :schedule_trip, to: 'employee_trips#schedule_trip'
      post :schedule, to: 'employee_schedules#update'
      post :schedule_trip_update, to: 'employee_trips#schedule_trip_update'
      get :invite, to: "employees#invite"
    end

    collection do
      get :guards
      post :validate
      post :ingest, to: 'ingest_job#create'
      get :get_geocode
      get :get_nodal_geocode
    end
  end

  resources :notifications do
    member do
      post :archive
      post :move_driver_to_next_step
      post :resolve
      post :mark_notifications_as_old
    end
  end
  resources :invoices do
    member do
      post :update_status
      post :ba_update_status
    end
    collection do
      post :generate_invoice_for_trips
      get :invoice_details
      get :ba_invoice_details
      get :trip_data
      get :bill_data
      get :completed_trips
      get :completed_vehicles
      get :customer_invoices
      get :ba_invoices
      get :ba_trip_data
      get :ba_bill_data
      get :download
      get :ba_download
      post :delete_customer_invoices
      post :delete_ba_invoices
    end
  end

  resources :zones
  resources :vehicles do
    collection do
      post :vehicle_break_down_approve_decline
    end
    member do
      post :vehicle_broke_down
      post :vehicle_ok
      get :checklist
      post :update_checklist
    end
  end
  
  get "/billing/detail_invoice/:id", to: "invoices#detail_invoice"

  resources :sites do
    member do
      put :update_site      
    end
    collection do
      post :details
    end
  end

  resource :reports do
    member do
      get :active
      get :completed
      get :utilization
      get :exceptions_summary
      get :operations_summary
      get :ota_summary
      get :otd_summary
      get :no_show_and_cancellations
      get :panic_alarms
      get :trip_logs
      get :employee_logs
      get :vehicle_deployment
      get :ota
      get :otd
      get :employee_no_show
      get :employee_satisfaction
      get :employee_activity
      get :driver_activity
      get :drivers_trip_summary
      get :employee_wise_no_show
      get :shift_fleet_utilisation_summary
      get :shift_wise_no_show
      get :trip_wise_driver_exception
      get :vendor_trip_distribution
      get :download
      post :send_report
    end
  end
  resources :analytics, :only =>[:index],  defaults: {format: :json}

  resources :trip_locations, :only =>[:index],  defaults: {format: :json}

  resources :driver_first_pickups, :only =>[:index],  defaults: {format: :json}

  # --------------------------- Trips --------------------------------

  resources :trips do
    collection do
      post :drivers_timeline
      get :guards_list      
      # post :ingest_manifest, to: 'ingest_manifest_job#create'
      # get 'ingest_manifest_jobs/:id', to: 'ingest_manifest_job#show'
      resources :ingest_job
      post :auto_assign_driver
      post :auto_assign_guard
    end
    member do
      get :employee_trips
      post :get_drivers
      post :update_employee_trips
      post :assign_driver
      post :assign_driver_submit
      post :assign_driver_exception
      post :unassign_driver_submit
      get :complete_with_exception
      post :complete_with_exception_submit
      post :book_ola_uber
      post :book_ola_uber_submit
      post :add_guard_to_trip
      get :trip_details
      get :search_driver
      post :annotate_trip
    end
  end

  resources :employee_trips do
    member do
      get :share    
      post :remove_passenger  
    end
    collection do
      get :get_clusters
      post :auto_cluster_trips
      get :add_passengers
      post :add_passengers_submit
      delete :cancel_trip_request
      post :create_trip_rosters
      get :first_shift
      post :unique_shifts
      post :set_exception_status
    end
  end

  resources :bus_trips do
    member do
      post :toggle_state
    end
  end

  resources :bus_trip_routes
  
  get :employee_trips_changes, to: 'employee_trips#employee_trip_change_requests'
  post :employee_trips_changes, to: 'employee_trips#trip_change_request_response'

  get :driver_requests, to: 'drivers#get_driver_requests'
  post :driver_requests, to: 'drivers#update_driver_requests'

  # ------------------------- api v1 ----------------------------------
  namespace :api, defaults: {format: 'json'} do
    scope :v1, module: 'v1' do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks],
                                  controllers: {
                                      sessions: 'overrides/sessions',
                                      passwords: 'overrides/passwords'
                                  }

      resources :drivers, only: :show do
        member do
          get 'upcoming_trip'
          get 'last_trip_request'
          post 'on_duty'
          get 'off_duty'
          post 'change_vehicle'
          get 'report_to_duty'
          get 'vehicle_ok_now'
          get 'trip_history'
          post 'update_current_location'
          post 'heart_beat'
          post 'driver_request'
          post 'vehicle_info'
          post 'call_operator'
        end
      end
      resources :trips do
        member do
          post :assign_driver
        end
      end
      resources :employee_trips, except: :destroy do
        member do
          post 'cancel'
          post 'rate'
          post 'exception'
          get 'dismiss_trip'
          post 'trip_rated'
          post 'employee_on_board'
        end
      end

      resources :employees, only: [ :show, :update ] do
        member do
          get 'upcoming_trip'
          get 'last_completed_trip'
          get 'upcoming_trips'
          get 'trip_history'
          post 'call_operator'
          post 'update_user_status'
        end
      end

      resources :trips, only: :show do
        member do
          get 'accept_trip_request'
          get 'decline_trip_request'
          get 'start'
          post 'verify_driver_image'
          post 'change_status_request_assigned'
          scope :trip_routes do
            post 'on_board'
            post 'driver_arrived'
            post 'completed'
            post 'resolve_exception'
            post 'not_on_board'
          end
        end
      end

      resources :trip_routes do
        member do
          post 'initiate_call'
          get 'employee_no_show'
        end
      end

      resources :trip_route_exceptions do
        member do
          get 'resolve'
        end
      end
      get :verify_email, to: "users#verify_email"
      post :set_password, to: "users#set_password"
    end
  end

  resources :employer_shift_managers
  resources :operator_shift_managers

app/models/site.rb
require 'services/google_service'

class Site < ApplicationRecord
  extend AdditionalFinders
  DATATABLE_PREFIX = 'site'

  belongs_to :employee_company
  has_many :employees
  has_many :drivers
  has_many :trips
  has_many :services, :dependent => :destroy
  has_many :shifts

  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :employee_company, presence: true

  def location
    [ latitude, longitude ]
  end

  def location_hash
    {:lat => latitude.to_f, :lng => longitude.to_f}
  end

  def generate_invoice
    @invoice = Invoice.new(:company_id => self.employee_company_id, 
                      :date => Time.now(),
                      :status  => 'new'
                      )
    @service = Service.where(:site => self).first
    status = ['completed', 'canceled']
    @trips = Trip.where(:status => status).where(:site => self).where(:scheduled_date => (Time.now - 1.day).beginning_of_month..(Time.now - 1.day).end_of_month)
    @trips.each do |trip|
      if trip.cancel_status != 'Driver Didn’t Complete'
        bill_amount = generate_invoice_for_trip(trip, @service)
        Trip.where(:id => trip.id).update_all({:toll=>bill_amount['toll'], :penalty => bill_amount['penalty'], :amount => bill_amount['amount'], :paid => 1})
        TripInvoice.create!(:invoice_id => @invoice.id, 
                        :trip_id => trip.id,
                        :trip_amount => bill_amount['amount'],
                        :trip_penalty => bill_amount['penalty'],
                        :trip_toll => bill_amount['toll'],
                        :vehicle_rate_id => 0,
                        :zone_rate_id => 0
                        )
      end
    end    
  end

  protected
  # Update site address coordinates on every save
  def set_site_coordinates
    return errors.add(:address, 'Please provide the address.') if address.blank?

    self.latitude = nil
    self.longitude = nil

    # Geocoding an address
    results = GoogleService.new.geocode(address).first

    unless results.nil? || ! results.key?(:geometry)
      coordinates = results[:geometry][:location]
      self.latitude = coordinates[:lat]
      self.longitude = coordinates[:lng]
    end
  end

  def generate_invoice_for_trip(trip, service)
    #TODO ignoring overage as of now
    vehicle = Vehicle.where(:id => trip.vehicle_id).first
    billing_zone = trip.employee_trips.collect {|employee_trip| employee_trip.employee[:billing_zone]}.uniq
    is_guard = 0
    vehicle_rate = nil
    zone_rate = nil
    if trip.trip_type == 0
      is_guard = trip.employee_trips.first.employee.is_guard
    else
      is_guard = trip.employee_trips.last.employee.is_guard
    end
    if service.billing_model == 'Fixed Rate per Trip'      
      if service.vary_with_vehicle
        puts "********** case trip - vehicle ***********"
        vehicle_rate = VehicleRate.where(:service_id => service.id).where(:vehicle_capacity => vehicle.seats).where(:ac => vehicle.ac).first        
      else
        puts "********** case trip - NO vehicle ***********"
        vehicle_rate = VehicleRate.where(:service_id => service.id).where(:vehicle_capacity => 0).first        
      end
      zone_rate = ZoneRate.where(:vehicle_rate_id => vehicle_rate.id).where(:name => 'Default').first
    elsif service.billing_model == 'Fixed Rate per Zone'
      if service.vary_with_vehicle
        puts "********** case Zone - vehicle ***********"        
        vehicle_rate = VehicleRate.where(:service_id => service.id).where(:vehicle_capacity => vehicle.seats).where(:ac => vehicle.ac).first        
      else
        puts "********** case zone - NO vehicle ***********"
        vehicle_rate = VehicleRate.where(:service_id => service.id).where(:vehicle_capacity => 0).first
      end
      zone_rate = ZoneRate.where(:vehicle_rate_id => vehicle_rate.id).where(:name => billing_zone).order(rate: :desc).first
    end
    calculate_cost(vehicle_rate, zone_rate, is_guard)
  end

  def calculate_cost(vehicle_rate, zone_rate, is_guard)
    amount = 0
    if is_guard
      amount = zone_rate[:rate] + zone_rate[:guard_rate]
    else
      amount = zone_rate[:rate]
    end    
    bill_amount = {
      'amount' => amount,
      'penalty' => 0,
      'toll' => 0,
      'zone_rate_id' => zone_rate[:id],
      'vehicle_rate_id' => vehicle_rate[:id]
    }
  end  
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.slim
= simple_form_for @employee, html: {:'data-validate' => 'form', class: 'modal-form live-validation', :multipart => true, id: id}, :url => url, :method => meth, remote: remote do |f|
    .row
      .col-md-4
        = f.input :f_name, label: 'First Name', required: true, wrapper_html: { class: 'search-match' }, input_html: { data: { "match-user" => "name" } }
      .col-md-4
        = f.input :m_name, label: 'Middle Name', wrapper_html: { class: 'search-match' }, input_html: { data: { "match-user" => "name" } }
      .col-md-4
        = f.input :l_name, label: 'Last name', required: true, wrapper_html: { class: 'search-match' }, input_html: { data: { "match-user" => "name" } }
    .row
      - unless @is_guard
        .col-md-4
          = f.input :email, label: 'Email', required: true, wrapper_html: { class: 'search-match' }, input_html: { data: { "match-user" => "email" } }
      .col-md-4
        = f.input :phone, as: :tel, label: 'Phone', required: true, wrapper_html: { class: 'search-match' }, input_html: { data: { "match-user" => "phone" } }
      .col-md-4
        = f.simple_fields_for :entity_attributes, @employee.entity do |ui|
          = ui.association :employee_company, label: 'Company', prompt: false, required: true, prompt: "Choose a Company"
      - if @is_guard
        .col-md-4
          = f.input :shift_ids, collection: Shift.active.map { |x| [x.name, x.id] }, input_html: { multiple: true, class: "multiple-select-ui" }, wrapper_html: { class: "provisioning-multiselect" }
    - unless @is_guard
      .row
        .col-md-4
          = f.input :shift_ids, collection: Shift.active.map { |x| [x.name, x.id] }, input_html: { multiple: true, class: "multiple-select-ui" }, wrapper_html: { class: "provisioning-multiselect" }
        .col-md-4
          = f.input :process_code, label: 'Process Code'
        .col-md-4
          = f.simple_fields_for :entity_attributes, @employee.entity do |ui|
            = ui.input :line_manager_id, collection: @line_managers, label: "Line Manager", prompt: "Choose a Line Manager"
    = f.simple_fields_for :entity_attributes, @employee.entity do |ui|
      -if @is_guard
        = ui.input :is_guard, as: 'hidden', input_html: { value: '1' }
      .row
        .col-md-4.group-label.text-right
          -if @is_guard
            span.field-label
              | Guard attributes:
          -else
            span.field-label
              | Employee attributes:
        .col-md-4
          = ui.input :employee_id, label: 'Employee id', required: true
        .col-md-4
          - if @is_guard
            = ui.input :gender, as: 'hidden', input_html: { value: 'male' }
            = ui.association :site, label: 'Site', wrapper_html: { class: 'site' }, prompt: false, required: true, prompt: "Choose Site"
          -else
            = ui.input :gender, required: true, label: 'Gender', prompt: false, collection: [['Male', 'male'], ['Female', 'female']], prompt: "Choose Gender"
      - unless @is_guard
        .row
          .col-md-8.col-md-offset-4
            label.control-label[for="user_avatar"]
              | Image
            .fileinput[data-provides="fileinput" class="#{@employee.avatar.present? ? 'fileinput-exists' : 'fileinput-new'}"]
              .file-wrap-block
                input[type="hidden" value="" name="fileinput_widget"]
                .file-input-wrap
                  .input-group
                    .form-control[data-trigger="fileinput"]
                      i.glyphicon.glyphicon-file.fileinput-exists
                      span.fileinput-filename
                        - if @employee.avatar.present?
                          = @employee.avatar_file_name
                    span.input-group-btn
                      button.btn.btn-default.fileinput-exists[rel="tooltip" title="" data-dismiss="fileinput" data-original-title="remove"]
                        i.fa.fa-times
                      button.btn.btn-inverse.btn-file
                        span.fileinput-new
                          | Choose image
                        span.fileinput-exists
                          | Change
                        = f.input :avatar, as: :file, label: false, :wrapper => false, input_html: {class: 'file-upload', accept: 'image/*'}
      - unless @is_guard
        .row
          .col-md-4.col-md-offset-4
            = ui.association :site, label: 'Site', wrapper_html: { class: 'site' }, prompt: false, required: true, prompt: "Choose Site"
          .col-md-4
            = ui.input :billing_zone, required: false, label: 'Billing Zone', prompt: false, collection: @billing_zones, prompt: "Choose Billing Zone"
      .row[style="margin-bottom:0px"]
        .col-md-6.col-md-offset-4.employee-home-address
          .input-group
            = ui.input :home_address, label: "#{@is_guard ? 'Pick-Up Address' : 'Home Address'}", required: true
            span.input-group-btn
              /!button.btn.btn-primary type="button"  Go!
              = link_to 'Geocode', get_geocode_employees_path, class: "geo_code btn btn-primary"
        .col-md-1
          = ui.input :home_address_latitude, label: 'Lat', required: true, input_html: { class: "geo-code-numner-field" }
        .col-md-1
          = ui.input :home_address_longitude, label: 'Long', required: true, input_html: { class: "geo-code-numner-field" }
      .row
        .col-md-4.col-md-offset-4
          = ui.input :landmark, label: 'Area/Landmark'
        .col-md-4
          = ui.input :nodal_name, label: 'Nodal Name'
      .row[style="margin-bottom:0px"]
        .col-md-6.col-md-offset-4.employee-home-address
          .input-group
            = ui.input :nodal_address, label: "#{@is_guard ? 'Nodal Address' : 'Nodal Address'}"
            span.input-group-btn
              /!button.btn.btn-primary type="button"  Go!
              = link_to 'Geocode', get_nodal_geocode_employees_path, class: "nodal_geo_code btn btn-primary"
        .col-md-1
          = ui.input :nodal_address_latitude, label: 'Lat', input_html: { class: "geo-code-numner-field" }
        .col-md-1
          = ui.input :nodal_address_longitude, label: 'Long', input_html: { class: "geo-code-numner-field" }
      - unless @is_guard
        .row
          .col-xs-4.col-md-4.col-md-offset-4
            = ui.input :bus_travel, input_html: {class: "bus_travel"}
          .col-md-4
            = ui.association :bus_trip_route, label: 'Bus Stop', prompt: false, required: false, prompt: "Choose Bus Stop"

      ul.match-result style=("display: none;")

/! Delete Modal
#employeeDeleteModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h4.modal-title Delete Employee
      .modal-body
        p Are you sure you wish to delete this employee?
      .modal-footer
        = link_to 'Delete', @employee.entity, method: :delete, class: "btn btn-danger btn-sm"
        button.btn.btn-sm.btn-default data-dismiss="modal" type="button"  Close

app/views/employees/_modal_employees_edit.html.slim
= render :partial => 'employees/form', :locals => {:url => employee_path, :meth => 'PATCH', remote: true, id: @is_guard ? "form-guards" : "form-employees"}

app/views/employees/_modal_employees_new.html.slim
#m-employees-new
  = render :partial => 'employees/form', :locals => {:url => employees_path, :meth => 'POST', :remote => true, id: @is_guard ? "form-guards" : "form-employees"}

app/views/employees/edit.js.slim
| $("#{@is_guard ? '#guards' : '#employees'} .table-content-edit").html('');
| $("#{@is_guard ? '#guards' : '#employees'} .table-content-edit").html('
= j render :partial => 'employees/modal_employees_edit', :locals => {:employee => @employee, line_managers: @line_managers}
| ');
| datepickerInit();
| initSelectbox();

| $('.multiple-select-ui').multiselect({
|   includeSelectAllOption: true
| });

app/views/employees/new.js.slim
| $("#{@is_guard ? '#guards' : '#employees'} .table-content-edit").html('');
| $("#{@is_guard ? '#guards' : '#employees'} .table-content-edit").html('
= j render :partial => 'employees/modal_employees_new', :locals => {:employee => @employee, line_managers: @line_managers}
| ');
| datepickerInit();
| initSelectbox();

| $('.multiple-select-ui').multiselect({
|   includeSelectAllOption: true
| });