config/routes.rb
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  # root 'dashboard#index'


  root :to => 'trips#index', :constraints => lambda { |request| request.env['warden'].user&.role == 'line_manager' }
  root :to => 'dashboard#index'

  resources :dashboard do
    collection do
      get :ota
      get :costs
      get :exceptions
      get :completed_trips
      get :fleet_utilization
    end
  end

  # ------------------------- Companies ------------------------------

  resources :logistics_companies do
    collection do
      get :get_all
    end
  end
  put '/logistics_companies/operator/:id', to: 'logistics_companies#operator_edit'
  delete '/logistics_companies/operator/:id', to: 'logistics_companies#operator_delete'    
  
  resources :employee_companies do
    collection do
      get :get_all
    end
  end

  resources :business_associates do
    member do
      put :update_ba
    end
    collection do
      post :details
    end
  end

  # --------------------------- Users --------------------------------
  resources :user
  get 'users', to: 'user#index'

  get '/profile', to: 'home#profile_edit', as: :user_profile_edit
  get '/site_list', to: 'sites#site_list'
  patch '/profile', to: 'home#profile_update', as: :user_profile_update
  get '/initiate_call', to: 'home#initiate_call'
  post '/update_last_active_time', to: 'home#update_last_active_time'
  post '/exotel_callback', to: 'home#exotel_callback'
  get '/badge_count', to: 'home#badge_count'
  post '/auto_cluster', to: 'home#auto_cluster'
  post '/decluster', to: 'employee_clusters#decluster'
  post '/auto_clustering_via_service', to: 'employee_trips#auto_clustering_via_service'
  get '/offline_sms', to: 'home#offline_sms_get'
  post '/offline_sms', to: 'home#offline_sms_post'
  get '/sorted_routes', to: 'home#sorted_routes'

  get '/release_info', to: 'home#release_info'

  resources :operators
  resources :employers
  resources :line_managers do
    member do
      get :invite
      get :edit_list
      post :update_employee_list
    end
  end
  resources :transport_desk_managers
  resources :drivers do
    member do
      get :invite
      post :stop_on_leave
      get :checklist
      post :update_checklist
    end
    post :validate, on: :collection
  end
  resources :employees do
    member do
      get :schedule, to: 'employee_schedules#edit'
      get :trips, to: 'employee_trips#trips'
      get :schedule_trip, to: 'employee_trips#schedule_trip'
      post :schedule, to: 'employee_schedules#update'
      post :schedule_trip_update, to: 'employee_trips#schedule_trip_update'
      get :invite, to: "employees#invite"
    end

    collection do
      get :guards
      post :validate
      post :ingest, to: 'ingest_job#create'
      get :get_geocode
      get :get_nodal_geocode
    end
  end

  resources :notifications do
    member do
      post :archive
      post :move_driver_to_next_step
      post :resolve
      post :mark_notifications_as_old
    end
  end
  resources :invoices do
    member do
      post :update_status
      post :ba_update_status
    end
    collection do
      post :generate_invoice_for_trips
      get :invoice_details
      get :ba_invoice_details
      get :trip_data
      get :bill_data
      get :completed_trips
      get :completed_vehicles
      get :customer_invoices
      get :ba_invoices
      get :ba_trip_data
      get :ba_bill_data
      get :download
      get :ba_download
      post :delete_customer_invoices
      post :delete_ba_invoices
    end
  end

  resources :zones
  resources :vehicles do
    collection do
      post :vehicle_break_down_approve_decline
    end
    member do
      post :vehicle_broke_down
      post :vehicle_ok
      get :checklist
      post :update_checklist
    end
  end
  
  get "/billing/detail_invoice/:id", to: "invoices#detail_invoice"

  resources :sites do
    member do
      put :update_site      
    end
    collection do
      post :details
    end
  end

  resource :reports do
    member do
      get :active
      get :completed
      get :utilization
      get :exceptions_summary
      get :operations_summary
      get :ota_summary
      get :otd_summary
      get :no_show_and_cancellations
      get :panic_alarms
      get :trip_logs
      get :employee_logs
      get :vehicle_deployment
      get :ota
      get :otd
      get :employee_no_show
      get :employee_satisfaction
      get :employee_activity
      get :driver_activity
      get :drivers_trip_summary
      get :employee_wise_no_show
      get :shift_fleet_utilisation_summary
      get :shift_wise_no_show
      get :trip_wise_driver_exception
      get :vendor_trip_distribution
      get :download
      post :send_report
    end
  end
  resources :analytics, :only =>[:index],  defaults: {format: :json}

  resources :trip_locations, :only =>[:index],  defaults: {format: :json}

  resources :driver_first_pickups, :only =>[:index],  defaults: {format: :json}

  # --------------------------- Trips --------------------------------

  resources :trips do
    collection do
      post :drivers_timeline
      get :guards_list      
      # post :ingest_manifest, to: 'ingest_manifest_job#create'
      # get 'ingest_manifest_jobs/:id', to: 'ingest_manifest_job#show'
      resources :ingest_job
      post :auto_assign_driver
      post :auto_assign_guard
    end
    member do
      get :employee_trips
      post :get_drivers
      post :update_employee_trips
      post :assign_driver
      post :assign_driver_submit
      post :assign_driver_exception
      post :unassign_driver_submit
      get :complete_with_exception
      post :complete_with_exception_submit
      post :book_ola_uber
      post :book_ola_uber_submit
      post :add_guard_to_trip
      get :trip_details
      get :search_driver
      post :annotate_trip
    end
  end

  resources :employee_trips do
    member do
      get :share    
      post :remove_passenger  
    end
    collection do
      get :get_clusters
      post :auto_cluster_trips
      get :add_passengers
      post :add_passengers_submit
      delete :cancel_trip_request
      post :create_trip_rosters
      get :first_shift
      post :unique_shifts
      post :set_exception_status
    end
  end

  resources :bus_trips do
    member do
      post :toggle_state
    end
  end

  resources :bus_trip_routes
  
  get :employee_trips_changes, to: 'employee_trips#employee_trip_change_requests'
  post :employee_trips_changes, to: 'employee_trips#trip_change_request_response'

  get :driver_requests, to: 'drivers#get_driver_requests'
  post :driver_requests, to: 'drivers#update_driver_requests'

  # ------------------------- api v1 ----------------------------------
  namespace :api, defaults: {format: 'json'} do
    scope :v1, module: 'v1' do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks],
                                  controllers: {
                                      sessions: 'overrides/sessions',
                                      passwords: 'overrides/passwords'
                                  }

      resources :drivers, only: :show do
        member do
          get 'upcoming_trip'
          get 'last_trip_request'
          post 'on_duty'
          get 'off_duty'
          post 'change_vehicle'
          get 'report_to_duty'
          get 'vehicle_ok_now'
          get 'trip_history'
          post 'update_current_location'
          post 'heart_beat'
          post 'driver_request'
          post 'vehicle_info'
          post 'call_operator'
        end
      end
      resources :trips do
        member do
          post :assign_driver
        end
      end
      resources :employee_trips, except: :destroy do
        member do
          post 'cancel'
          post 'rate'
          post 'exception'
          get 'dismiss_trip'
          post 'trip_rated'
          post 'employee_on_board'
        end
      end

      resources :employees, only: [ :show, :update ] do
        member do
          get 'upcoming_trip'
          get 'last_completed_trip'
          get 'upcoming_trips'
          get 'trip_history'
          post 'call_operator'
          post 'update_user_status'
        end
      end

      resources :trips, only: :show do
        member do
          get 'accept_trip_request'
          get 'decline_trip_request'
          get 'start'
          post 'verify_driver_image'
          post 'change_status_request_assigned'
          scope :trip_routes do
            post 'on_board'
            post 'driver_arrived'
            post 'completed'
            post 'resolve_exception'
            post 'not_on_board'
          end
        end
      end

      resources :trip_routes do
        member do
          post 'initiate_call'
          get 'employee_no_show'
        end
      end

      resources :trip_route_exceptions do
        member do
          get 'resolve'
        end
      end
      get :verify_email, to: "users#verify_email"
      post :set_password, to: "users#set_password"
    end
  end

  resources :employer_shift_managers
  resources :operator_shift_managers

  get "/shift_times/:id/schedule_time", to: "shift_times#schedule_time"
  get "/shift_times/:id/timings", to: "shift_times#timings"
  post "/shift_times/:id/update_time", to: 'shift_times#update_time'

  # ------------------------- api v2 ----------------------------------
  namespace :api, defaults: {format: 'json'} do
    scope :v2, module: 'v2' do
      resources :business_associates do 
        collection do
          get :search
        end
      end
      resources :drivers do
      collection do
        get :search
        post :validate_licence_number
        post :validate_contact_number
      end
    end
      resources :vehicles do
        collection do
          get :search
          get :find_category_seat_by_vehicle

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:edit, :update, :destroy, :vehicle_broke_down, :vehicle_ok]
  before_action :only_admin_and_operator, only: [:create, :update]

  def index
    # @vehicles = params[:search_input].present? && params[:search_by].present? ? Vehicle.ransack(Searchables::VehicleSearchable.new(params[:search_input]).send("by_#{params[:search_by]}")).result.order("plate_number ASC") : Vehicle.all
    respond_to do |format|
      format.html
      format.json { render json: VehiclesDatatable.new(view_context) }
    end
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save
    @errors = @vehicle.errors.full_messages.to_sentence
    @datatable_name = "vehicles"

    respond_to do |format|
      format.js { render file: "shared/create" }
      format.html { redirect_to provisioning_path(anchor: @datatable_name) }
    end
  end

  def edit

  end

  def update
    @vehicle.update(vehicle_params)
    @errors = @vehicle.errors.full_messages.to_sentence
    @datatable_name = "vehicles"

    respond_to do |format|
      format.js { render file: "shared/create" }
      format.html { redirect_to provisioning_path(anchor: @datatable_name) }
    end
  end

  def destroy
    if current_user.admin? || current_user.operator?
      @vehicle.destroy
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end

  def vehicle_broke_down
    # Create a new trip request for car brokw down
    if @vehicle.driver.present?

      @driver_request = @vehicle.driver.driver_requests.new(
          reason: '',
          request_type: 'car_broke_down',
          driver: @driver,
          request_date: Time.now
      )
      @driver_request.vehicle = @vehicle

      @driver_request.save

      #Approve the car broke down request by the driver
      @driver_request.approve!
    else
      @vehicle.vehicle_broke_down!
    end
  end

  def vehicle_ok
    if params['request_id'].present?
      driver_request = DriverRequest.find(params['request_id'])
      if driver_request.present?
        driver_request.cancel_approved!
      end
    else
      @vehicle.vehicle_ok!
    end
  end

  def checklist
    @checklist = Checklist.find(params[:id])
    @vehicle = @checklist.vehicle
    @checklist_progress = ((@checklist.checklist_items.checked.size.to_f / @checklist.checklist_items.size) * 100).round
    @total_fields = @checklist.checklist_items.size
  end

  def update_checklist
    checklist = Checklist.find params[:id]
    checklist.update_checklist_items(checklist_params)
    render json: true, status: 200
  end
  
  def vehicle_break_down_approve_decline
    if params['request_id'].present?
      driver_request = DriverRequest.find(params['request_id'])
      if params['approve'] == '1'
        driver_request.approve!
      else
        driver_request.decline!
      end
    end
  end

  private
  def checklist_params
    params.require(:checklist_items).permit!
  end
    
  def set_vehicle
    @vehicle = Vehicle.find_by_prefix(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(
        :driver_id, :business_associate_id, :name, :make, :plate_number, :model, :colour, :photo,
        :driver_name, :rc_book_no, :registration_date, :insurance_date, :fuel_type, :permit_type,
        :permit_validity_date, :puc_validity_date, :fc_validity_date, :ac, :make_year, :induction_date,
        :odometer, :spare_type, :first_aid_kit, :tyre_condition, :device_id,
        :seats, :fuel_level, :plate_condition
    )
  end

  def only_admin_and_operator
    return if current_user.admin? || current_user.operator?
    flash[:error] = 'You have not permissions for update vehicle'
    redirect_to provisioning_path(anchor: 'vehicles')
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_edit.html.slim
= render :partial => 'vehicles/form', :locals => {:vehicle => @vehicle, :url => vehicle_path(@vehicle), :method => 'PUT'}

app/views/vehicles/_form.html.slim
= simple_form_for @vehicle, html: {'data-validate' => 'form', :class => 'modal-form vehicle-form', :id => 'form-vehicles'}, :url => url, remote: true, :method => method do |f|
  .row
    .col-md-15-2.group-label.text-right
      span.field-label
        | Info:
    .col-md-15-3
      = f.association :business_associate, label: 'Choose associate', prompt: false, input_html: {class: 'selectboxit', :'placeholder' => ''}, required: true
    .col-md-15-3
      = f.input :make, label: 'Make', required: true
  .row
    .col-md-15-6.col-md-15-offset-2
      label.control-label[for="user_avatar"]
        | Image
      .fileinput[data-provides="fileinput" class="#{@vehicle.photo.present? ? 'fileinput-exists' : 'fileinput-new'}"]
        .file-wrap-block
          input[type="hidden" value="" name="fileinput_widget"]
          .file-input-wrap
            .input-group
              .form-control[data-trigger="fileinput"]
                i.glyphicon.glyphicon-file.fileinput-exists
                span.fileinput-filename
                  - if @vehicle.photo.present?
                      = @vehicle.photo_file_name
              span.input-group-btn
                button.btn.btn-default.fileinput-exists[rel="tooltip" title="" data-dismiss="fileinput" data-original-title="remove"]
                  i.fa.fa-times
                button.btn.btn-inverse.btn-file
                  span.fileinput-new
                    | Choose image
                  span.fileinput-exists
                    | Change
                  = f.input :photo, as: :file, label: false, :wrapper => false, input_html: {class: 'file-upload', accept: 'image/*'}
  .row
    .col-md-15-3.col-md-15-offset-2
      = f.input :plate_number, label: 'Plate Number', required: true
    .col-md-15-3
      = f.input :model, label: 'Model', required: true
    .col-md-15-3
      = f.input :colour, label: 'Colour', required: true
  .row
    .col-md-15-3.col-md-15-offset-2
      = f.input :rc_book_no, label: 'Rc Book No', required: true
    .col-md-15-3
      = f.input :registration_date, as: :string, label: 'Registration Date', required: true, input_html: {data: {input: 'datepicker'}, :value => @vehicle.registration_date.try(:strftime, '%d/%m/%Y')}
    .col-md-15-3
      = f.input :insurance_date, as: :string, label: 'Insurance Date', required: true, input_html: {data: {input: 'datepicker'}, :value => @vehicle.insurance_date.try(:strftime, '%d/%m/%Y')}
    .col-md-15-3
      = f.input :fuel_type, label: 'Fuel Type', required: true

  .row
    .col-md-15-3.col-md-15-offset-2
      = f.input :permit_type, label: 'Permit Type', required: true
    .col-md-15-3
      = f.input :permit_validity_date, as: :string, label: 'Permit Validity Date', required: true, input_html: {data: {input: 'datepicker'}, :value => @vehicle.permit_validity_date.try(:strftime, '%d/%m/%Y')}
    .col-md-15-3
      = f.input :puc_validity_date, as: :string, label: 'Puc Validity Date', required: true, input_html: {data: {input: 'datepicker'}, :value => @vehicle.puc_validity_date.try(:strftime, '%d/%m/%Y')}
    .col-md-15-3
      = f.input :fc_validity_date, as: :string, label: 'Fc Validity Date', required: true, input_html: {data: {input: 'datepicker'}, :value => @vehicle.fc_validity_date.try(:strftime, '%d/%m/%Y')}
  .row
    .col-md-15-3.col-md-15-offset-2
      = f.input :seats, label: 'Seats', required: true
    .col-md-15-3
      = f.input :make_year, label: 'Make Year', required: true
    .col-md-15-3
      = f.input :induction_date, as: :string, label: 'Induction Date', required: true, input_html: {data: {input: 'datepicker'}, :value => @vehicle.induction_date.try(:strftime, '%d/%m/%Y')}
    .col-md-15-3
      = f.input :odometer, label: 'Odometer', required: true
  .row
    .col-md-15-3.col-md-15-offset-2
      = f.input :tyre_condition, label: 'Tyre Condition', required: true
    .col-md-15-3
      = f.input :device_id, label: 'Device ID', required: true
    .col-md-15-3
      = f.input :fuel_level, label: 'Fuel Level', required: true
    .col-md-15-3
      = f.input :plate_condition, label: 'Plate Condition', required: true
  .row
    .col-md-15-3.col-md-15-offset-2
      = f.input :ac, :wrapper => :checkbox_basic, required: true, :default => false
    .col-md-15-3
      = f.input :spare_type, :wrapper => :checkbox_basic, required: true
    .col-md-15-3
      = f.input :first_aid_kit, :wrapper => :checkbox_basic, required: true

app/views/vehicles/_new.html.slim
= render :partial => 'vehicles/form', :locals => {:vehicle => @vehicle, :url => vehicles_path(@vehicle), :method => 'POST'}

app/views/vehicles/checklist.js.slim
| $("#vehicle-checklist-modal").html('');
| $("#vehicle-checklist-modal").html('
= j render :partial => 'checklists/form', locals: { checklist: @checklist, obj: 'vehicle', total_fields: @total_fields, progress: @checklist_progress, id: "form-vehicle-checklist", url: update_checklist_vehicle_path}
| ');
| $("#driverChecklistModal").modal('show');

|$('#form-vehicle-checklist').submit(function(){
|   $("#driverChecklistModal").modal('hide');
|});

app/views/vehicles/edit.js.slim
| $("#vehicles .table-content-edit").html('');
| $("#vehicles .table-content-edit").html('
= j render :partial => 'vehicles/edit'
| ');
| datepickerInit();
| initSelectbox();

app/views/vehicles/new.js.slim
| $("#vehicles .table-content-edit").html('');
| $("#vehicles .table-content-edit").html('
= j render :partial => 'vehicles/new'
| ');
| datepickerInit();
| initSelectbox();