config/routes.rb
  # ------------------------- Companies ------------------------------

  resources :logistics_companies do
    collection do
      get :get_all
    end
  end
  put '/logistics_companies/operator/:id', to: 'logistics_companies#operator_edit'
  delete '/logistics_companies/operator/:id', to: 'logistics_companies#operator_delete'    
  
  resources :employee_companies do
    collection do
      get :get_all
    end
  end

  resources :business_associates do
    member do
      put :update_ba
    end
    collection do
      post :details
    end
  end

  # --------------------------- Users --------------------------------
  resources :user
  get 'users', to: 'user#index'

  get '/profile', to: 'home#profile_edit', as: :user_profile_edit
  get '/site_list', to: 'sites#site_list'
  patch '/profile', to: 'home#profile_update', as: :user_profile_update
  get '/initiate_call', to: 'home#initiate_call'
  post '/update_last_active_time', to: 'home#update_last_active_time'
  post '/exotel_callback', to: 'home#exotel_callback'
  get '/badge_count', to: 'home#badge_count'
  post '/auto_cluster', to: 'home#auto_cluster'
  post '/decluster', to: 'employee_clusters#decluster'
  post '/auto_clustering_via_service', to: 'employee_trips#auto_clustering_via_service'
  get '/offline_sms', to: 'home#offline_sms_get'
  post '/offline_sms', to: 'home#offline_sms_post'
  get '/sorted_routes', to: 'home#sorted_routes'

  get '/release_info', to: 'home#release_info'

  resources :operators
  resources :employers
  resources :line_managers do
    member do
      get :invite
      get :edit_list
      post :update_employee_list
    end
  end
  resources :transport_desk_managers
  resources :drivers do
    member do
      get :invite
      post :stop_on_leave
      get :checklist
      post :update_checklist
    end
    post :validate, on: :collection
  end
  resources :employees do
    member do
      get :schedule, to: 'employee_schedules#edit'
      get :trips, to: 'employee_trips#trips'
      get :schedule_trip, to: 'employee_trips#schedule_trip'
      post :schedule, to: 'employee_schedules#update'
      post :schedule_trip_update, to: 'employee_trips#schedule_trip_update'
      get :invite, to: "employees#invite"
    end

    collection do
      get :guards
      post :validate
      post :ingest, to: 'ingest_job#create'
      get :get_geocode
      get :get_nodal_geocode
    end
  end

  resources :notifications do
    member do
      post :archive
      post :move_driver_to_next_step
      post :resolve
      post :mark_notifications_as_old
    end
  end
  resources :invoices do
    member do
      post :update_status
      post :ba_update_status
    end
    collection do
      post :generate_invoice_for_trips
      get :invoice_details
      get :ba_invoice_details
      get :trip_data
      get :bill_data
      get :completed_trips
      get :completed_vehicles
      get :customer_invoices
      get :ba_invoices
      get :ba_trip_data
      get :ba_bill_data
      get :download
      get :ba_download
      post :delete_customer_invoices
      post :delete_ba_invoices
    end
  end

  resources :zones
  resources :vehicles do
    collection do
      post :vehicle_break_down_approve_decline
    end
    member do
      post :vehicle_broke_down
      post :vehicle_ok
      get :checklist
      post :update_checklist
    end
  end
  
  get "/billing/detail_invoice/:id", to: "invoices#detail_invoice"

  resources :sites do
    member do
      put :update_site      
    end
    collection do
      post :details
    end
  end

  resource :reports do
    member do
      get :active
      get :completed
      get :utilization
      get :exceptions_summary
      get :operations_summary
      get :ota_summary
      get :otd_summary
      get :no_show_and_cancellations
      get :panic_alarms
      get :trip_logs
      get :employee_logs
      get :vehicle_deployment
      get :ota
      get :otd
      get :employee_no_show
      get :employee_satisfaction
      get :employee_activity
      get :driver_activity
      get :drivers_trip_summary
      get :employee_wise_no_show
      get :shift_fleet_utilisation_summary
      get :shift_wise_no_show
      get :trip_wise_driver_exception
      get :vendor_trip_distribution
      get :download
      post :send_report
    end
  end
  resources :analytics, :only =>[:index],  defaults: {format: :json}

  resources :trip_locations, :only =>[:index],  defaults: {format: :json}

  resources :driver_first_pickups, :only =>[:index],  defaults: {format: :json}

  # --------------------------- Trips --------------------------------

  resources :trips do
    collection do
      post :drivers_timeline
      get :guards_list      
      # post :ingest_manifest, to: 'ingest_manifest_job#create'
      # get 'ingest_manifest_jobs/:id', to: 'ingest_manifest_job#show'
      resources :ingest_job
      post :auto_assign_driver
      post :auto_assign_guard
    end
    member do
      get :employee_trips
      post :get_drivers
      post :update_employee_trips
      post :assign_driver
      post :assign_driver_submit
      post :assign_driver_exception
      post :unassign_driver_submit
      get :complete_with_exception
      post :complete_with_exception_submit
      post :book_ola_uber
      post :book_ola_uber_submit
      post :add_guard_to_trip
      get :trip_details
      get :search_driver
      post :annotate_trip
    end
  end

  resources :employee_trips do
    member do
      get :share    
      post :remove_passenger  
    end
    collection do
      get :get_clusters
      post :auto_cluster_trips
      get :add_passengers
      post :add_passengers_submit
      delete :cancel_trip_request
      post :create_trip_rosters
      get :first_shift
      post :unique_shifts
      post :set_exception_status
    end
  end

  resources :bus_trips do
    member do
      post :toggle_state
    end
  end

  resources :bus_trip_routes
  
  get :employee_trips_changes, to: 'employee_trips#employee_trip_change_requests'
  post :employee_trips_changes, to: 'employee_trips#trip_change_request_response'

  get :driver_requests, to: 'drivers#get_driver_requests'
  post :driver_requests, to: 'drivers#update_driver_requests'

  # ------------------------- api v1 ----------------------------------
  namespace :api, defaults: {format: 'json'} do
    scope :v1, module: 'v1' do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks],
                                  controllers: {
                                      sessions: 'overrides/sessions',
                                      passwords: 'overrides/passwords'
                                  }

      resources :drivers, only: :show do
        member do
          get 'upcoming_trip'
          get 'last_trip_request'
          post 'on_duty'
          get 'off_duty'
          post 'change_vehicle'
          get 'report_to_duty'
          get 'vehicle_ok_now'
          get 'trip_history'
          post 'update_current_location'
          post 'heart_beat'
          post 'driver_request'
          post 'vehicle_info'
          post 'call_operator'
        end
      end
      resources :trips do
        member do
          post :assign_driver
        end
      end
      resources :employee_trips, except: :destroy do
        member do
          post 'cancel'
          post 'rate'
          post 'exception'
          get 'dismiss_trip'
          post 'trip_rated'
          post 'employee_on_board'
        end
      end

      resources :employees, only: [ :show, :update ] do
        member do
          get 'upcoming_trip'
          get 'last_completed_trip'
          get 'upcoming_trips'
          get 'trip_history'
          post 'call_operator'
          post 'update_user_status'
        end
      end

      resources :trips, only: :show do
        member do
          get 'accept_trip_request'
          get 'decline_trip_request'
          get 'start'
          post 'verify_driver_image'
          post 'change_status_request_assigned'
          scope :trip_routes do
            post 'on_board'
            post 'driver_arrived'
            post 'completed'
            post 'resolve_exception'
            post 'not_on_board'
          end
        end
      end

      resources :trip_routes do
        member do
          post 'initiate_call'
          get 'employee_no_show'
        end
      end

      resources :trip_route_exceptions do
        member do
          get 'resolve'
        end
      end
      get :verify_email, to: "users#verify_email"
      post :set_password, to: "users#set_password"
    end
  end

  resources :employer_shift_managers
  resources :operator_shift_managers

  get "/shift_times/:id/schedule_time", to: "shift_times#schedule_time"
  get "/shift_times/:id/timings", to: "shift_times#timings"
  post "/shift_times/:id/update_time", to: 'shift_times#update_time'

  # ------------------------- api v2 ----------------------------------
  namespace :api, defaults: {format: 'json'} do
    scope :v2, module: 'v2' do
      resources :business_associates do 
        collection do
          get :search
        end
      end
      resources :drivers do
      collection do
        get :search
        post :validate_licence_number
        post :validate_contact_number
      end
    end
      resources :vehicles do
        collection do
          get :search
          get :find_category_seat_by_vehicle
          get :validate_plate_number
          get :get_vehicle_model_data
        end
      end
      resources :drivers, only: :show do
        member do
          post 'update_current_location'
          get 'last_trip_request'
          post 'vehicle_info'
        end
      end
    end
  end

  resource :configurators, only: [:show, :edit, :update]
  get "/configurations", to: "configurators#index"
  put '/update_config', to: 'configurators#update_config'
  put '/update_system_config', to: 'configurators#update_system_config'

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authorize_actions, except: [:show, :send_report, :download]
  before_action :can_download_report, only: [:send_report, :download]
  before_action :set_report_download_config

  def show
    authorize!(:show, :reports)
  end

  # # Reports about Active trips
  # def active
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: Reports::ReportActiveTripsDatatable.new(view_context)}
  #   end
  # end

  # # Reports about Completed trips
  # def completed
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: Reports::ReportCompletedTripsDatatable.new(view_context)}
  #   end
  # end

  # # Reports Capacity Utilization table
  # def utilization
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: Reports::ReportUtilizationsDatatable.new(view_context)}
  #   end
  # end

  # # Reports Exceptions Summary table
  # def exceptions_summary
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: Reports::ExceptionsSummary.new(view_context)}
  #   end
  # end

  # Reports about Operations summary
  def operations_summary
    respond_to do |format|
      format.html
      format.json { render json: Reports::ReportOperationsSummaryDatatable.new(view_context)}
    end
  end

  # Reports Capacity On Time Arrivals
  def ota_summary
    render json: Reports::ReportOtaSummariesDatatable.new(view_context)
  end

  # Reports Exceptions On Time Departures
  def otd_summary
    render json: Reports::ReportOtdSummariesDatatable.new(view_context)
  end

  # Reports about On No Show and Cancellation
  def no_show_and_cancellations
    respond_to do |format|
      format.html
      format.json { render json: Reports::ReportNoShowAndCancellationsDatatable.new(view_context)}
    end
  end

  # Reports about Panic Alarms
  def panic_alarms
    respond_to do |format|
      format.html
      format.json { render json: Reports::ReportPanicAlarmsDatatable.new(view_context)}
    end
  end

  def trip_logs
    render json: Reports::ReportTripLogsDatatable.new(view_context)
  end

  def employee_logs
    render json: Reports::ReportEmployeeLogsDatatable.new(view_context)
  end

  def vehicle_deployment
    render json: Reports::ReportVehicleDeploymentsDatatable.new(view_context)
  end

  def ota
    render json: Reports::ReportOtasDatatable.new(view_context)
  end

  def otd
    render json: Reports::ReportOtdsDatatable.new(view_context)
  end

  def employee_no_show
    render json: Reports::ReportEmployeeNoShowsDatatable.new(view_context)
  end

  def employee_satisfaction
    render json: Reports::ReportEmployeeSatisfactionsDatatable.new(view_context)
  end

  def employee_activity
    render json: Reports::ReportEmployeeActivitiesDatatable.new(view_context)
  end

  def driver_activity
    render json: Reports::ReportDriverActivitiesDatatable.new(view_context)
  end

  def drivers_trip_summary
    render json: Reports::ReportDriversTripSummariesDatatable.new(view_context)
  end

  def employee_wise_no_show
    render json: Reports::ReportEmployeeWiseNoShowsDatatable.new(view_context)
  end

  def shift_fleet_utilisation_summary
    render json: Reports::ReportShiftFleetUtilisationSummariesDatatable.new(view_context)
  end

  def shift_wise_no_show
    render json: Reports::ReportShiftWiseNoShowsDatatable.new(view_context)
  end

  def trip_wise_driver_exception
    render json: Reports::ReportTripWiseDriverExceptionsDatatable.new(view_context)
  end

  def vendor_trip_distribution
    render json: Reports::ReportVendorTripDistributionsDatatable.new(view_context)
  end

  def send_report
    ReportWorker.perform_async(params)
    render json: true, status: 200
  end

  def download
    filename = "#{params[:report_name]}-#{Date.today}.csv"
    report_obj = Object.const_get("Reports::Report#{params[:report_name].camelize}Datatable").new(view_context)
    send_data report_obj.csv, filename: filename
  end

  private

  def authorize_actions
    return if current_ability.can?(:view, :all_reports)
    authorize!(:view, params[:action].to_sym)
  end

  def can_download_report
    return if current_ability.can?(:view, :all_reports)
    authorize!(:view, params[:action].to_sym)
    action_name = ["trip_logs", "employee_logs", "no_show_and_cancellations", "panic_alarms"].include?(params[:report_name]) ? params[:report_name] : params[:report_name].singularize
    authorize!(:view, action_name.to_sym)
  end

  def set_report_download_config
    conf = Configurator.where(request_type: 'reports_download_button').first
    @can_perform_download = conf.present? ? ActiveModel::Type::Boolean.new.cast(conf.value) : false
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def zero_if_raise
    begin
      result = yield
      result.to_f.nan? ? 0 : result
    rescue
      0
    end
  end

  def get_date_time(date, time, field_name="date")
    zone = ActiveSupport::TimeZone.new("Chennai")
    dat = DateTime.strptime("#{date} #{time}", "%Y-%m-%d %H:%M").in_time_zone(zone)
    field_name == "date" ? dat.strftime("%d-%m-%Y") : dat.strftime("%H:%M")
  end
end

app/views/reports/_driver_activity.html.slim
#driver-activity.tab-pane.fade.reports-section
  .col-md-12
    .col-md-6.hidden
      ul.date-filter
        li.filter-block.date-filter
          input#driver-activity-picker[class="form-control" type="text" name="employee-activity-date" value=""]
    .col-md-6.pull-right
      -if @can_perform_download
        a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'driver_activities')}" type="button"]
          | Download
      button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-driver-activity-table.table.table-striped
      thead
        tr.reports-table
          th
            | First Name
          th
            | Last Name
          th
            | Phone
          th
            | Driver License
          th
            | Last Used Vehicle
          th
            | Site
          th
            | Vendor ID
          th
            | # Sign Ins
          th
            | Current Sign In At
          th
            | Last Sign In At
          th
            | Last Active At
          th
            | Last Active
      tbody

  = render :partial => 'report_download_modal', locals: { report_name: 'driver_activities'}

app/views/reports/_employee_activity.html.slim
#employee-activity.tab-pane.fade.reports-section
  .col-md-12
    .col-md-6.hidden
      ul.date-filter
        li.filter-block.date-filter
          input#employee-activity-picker[class="form-control" type="text" name="employee-activity-date" value=""]
    .col-md-6.pull-right
      -if @can_perform_download
        a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'employee_activities')}" type="button"]
          | Download
      button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-employee-activity-table.table.table-striped
      thead
        tr.reports-table
          th
            | First Name
          th
            | Last Name
          th
            | Employee ID
          th
            | Phone
          th
            | Email
          th
            | Site
          th
            | # Sign Ins
          th
            | Current Sign In At
          th
            | Last Sign In At
          th
            | Last Active At
          th
            | Last Active
          th
            | Status
      tbody

  = render :partial => 'report_download_modal', locals: { report_name: 'employee_activities'}

app/views/reports/_employee_logs.html.slim
#employee-logs.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#employee-logs-picker[class="form-control" type="text" name="employee-logs-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'employee_logs')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-employee-logs-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Trip Id
          th
            | Status
          th
            | Shift Time
          th
            | Direction
          th
            | Employee Id            
          th
            | Rider Name
          th
            | Driver Name
          th
            | Operator
          th
            | Vehicle
          th
            | Planned ETA
          th
            | Notified ETA
          th
            | I Am Here
          th
            | Pick Up Time
          th
            | Wait Time (min)
          th
            | Drop Off Time
          th
            | Employee Status
          th
            | Exception Detail
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'employee_logs'}

app/views/reports/_employee_satisfaction.html.slim
#employee-satisfaction.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#employee-satisfaction-picker[class="form-control" type="text" name="employee-satisfaction-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'employee_satisfactions')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-employee-satisfaction-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Trip ID
          th
            | Status
          th
            | Direction
          th
            | Shift Time
          th
            | Vehicle
          th
            | Employee ID
          th
            | Employee
          th
            | Rating
          th
            | Additional Feedback
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'employee_satisfactions'}

app/views/reports/_otd.html.slim
#otd.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#otd-picker[class="form-control" type="text" name="otd-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'otds')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-otd-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Trip Id
          th
            | Status
          th
            | Driver
          th
            | Vehicle
          th
            | Vendor Name
          th
            | Shift Time
          th
            | Driver Arrival At Site (min)
          th
            | Scheduled Depature Time
          th
            | Actual Depature Time (min)
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'otds'}

app/views/reports/_otd_summary.html.slim
#otd-summary.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#otd-summary-picker[class="form-control" type="text" name="otd-summary-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'otd_summaries')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-otd-summary-table.table.table-bordered
      thead
        tr
          th
            | Date
          th
            | Shift Time
          th
            | Total Logouts
          th
            | Logouts Catered To          
          th
            | Logouts Canceled
          th
            | Delayed Arrivals
          th
            | Average Delay
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'otd_summaries'}

app/views/reports/_panic_alarms.html.slim
#panic-alarms.tab-pane.fade.reports-section  
  .col-md-12
    .col-md-6
      ul.date-filter
        li.filter-block.date-filter
          input#panic-alarms-picker[class="form-control" type="text" name="panic-alarms-date" value=""]
    .col-md-6.
      -if @can_perform_download
        a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'panic_alarms')}" type="button"]
          | Download
      button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-panic-alarms-table.table.table-bordered
      thead
        tr
          th
            | Date
          th
            | Manifest ID
          th
            | Driver
          th
            | Vehicle
          th
            | Employee ID
          th
            | Alarm Time
          th
            | Location
          th
            | Resolution Time
          th
            | Resolved By                                         
      tbody

  = render :partial => 'report_download_modal', locals: { report_name: 'panic_alarms'}

app/views/reports/_report_download_modal.html.slim
/! Report Download Modal
.reportDownloadModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h4.modal-title Download Report
      .modal-body
        | Email
        input name="email" class="email" type="text" /
      .modal-footer
        a.btn.btn-sm.send-report-button[href="#{send_report_reports_path(report_name: report_name)}" type="button"]
          | Submit
        button.btn.btn-sm.btn-default data-dismiss="modal" type="button"  Close

app/views/reports/_shift_fleet_utilisation_summary.html.slim
#shift-fleet-utilisation-summary.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#shift-fleet-utilisation-summary-picker[class="form-control" type="text" name="shift-fleet-utilisation-summary-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'shift_fleet_utilisation_summaries')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-shift-fleet-utilisation-summary-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Shift Time
          th
            | Direction
          th
            | Vehicle Deployed
          th
            | Total Capacity
          th
            | Planned Capacity
          th
            | Actual Capacity
          th
            | Load Factor
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'shift_fleet_utilisation_summaries'}

app/views/reports/_shift_wise_no_show.html.slim
#shift-wise-no-show.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#shift-wise-no-show-picker[class="form-control" type="text" name="shift-wise-no-show-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'shift_wise_no_shows')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-shift-wise-no-show-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Shift Time
          th
            | Direction
          th
            | Number Of Employees
          th
            | Number Of No Shows
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'shift_wise_no_shows'}

app/views/reports/_trip_logs.html.slim
#trip-logs.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#trip-logs-picker[class="form-control" type="text" name="trip-logs-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'trip_logs')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-trip-logs-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Trip Id
          th
            | Driver
          th
            | Operator
          th
            | Vehicle
          th
            | Shift Time
          th
            | Direction
          th
            | Actual Time
          th
            | Trip Created
          th
            | Trip Assigned
          th
            | Trip Accepted
          th
            | Trip Started
          th
            | Number Of Riders
          th
            | Distance (km)
          th
            | Duration (min)
          th
            | EmployeeStatus
          th
            | Exception Detail
          th
            | Vehicle Capacity
          th
            | Delta Time
      tbody

  = render :partial => 'report_download_modal', locals: { report_name: 'trip_logs'}

app/views/reports/_trip_wise_driver_exception.html.slim
#trip-wise-driver-exception.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#trip-wise-driver-exception-picker[class="form-control" type="text" name="trip-wise-driver-exception-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'trip_wise_driver_exceptions')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-trip-wise-driver-exception-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Trip ID
          th
            | Shift Time
          th
            | Direction
          th
            | Driver
          th
            | Vehicle
          th
            | Out-Of-Geofence Driver Arrived
          th
            | Out-Of-Geofence Pick Up
          th
            | Out-Of-Geofence Drop Off
          th
            | Panic Alert
          th
            | Car Broke Down
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'trip_wise_driver_exceptions'}

app/views/reports/_vehicle_deployment.html.slim
#vehicle-deployment.tab-pane.fade.reports-section
  .col-md-12
    .row
      .col-md-6
        ul.date-filter
          li.filter-block.date-filter
            input#vehicle-deployment-picker[class="form-control" type="text" name="vehicle-deployment-date" value=""]
      .col-md-6.
        -if @can_perform_download
          a.btn.btn-sm.report-download-button.btn-fixed-width[href="#{download_reports_path(report_name: 'vehicle_deployments')}" type="button"]
            | Download
        button.btn.btn-sm.report-modal-button data-toggle="modal" type="button"  Send Email
  .col-md-12.table-responsive.table-responsive-datatables
    table#reports-vehicle-deployment-table.table.table-striped
      thead
        tr.reports-table
          th
            | Date
          th
            | Vendor Name
          th
            | Shift Time
          th
            | Direction
          th
            | Vehicle Deployed
      tbody
  = render :partial => 'report_download_modal', locals: { report_name: 'vehicle_deployments'}